### POST 의료진 등록
POST http://localhost:3000/doctors
Content-Type: application/json

{
  "name": "정의사",
  "department": "피부과",
  "profileImage": "/images/jung.jpg",
  "description": "피부 질환 전문"
}

### POST 의료진 등록
DELETE http://localhost:3000/doctors
Content-Type: application/json

{
  "name": "정의사",
  "department": "피부과"
}


### POST 의료진 등록
PUT http://localhost:3000/doctors/2
Content-Type: application/json

{
  "name": "업데이트된 김의사",
  "department": "심장내과",
  "profileImage": "/images/kim_new.jpg",
  "description": "심장 전문으로 변경됨"
}




###상담등록
POST http://localhost:3000/consultations
Content-Type: application/json

{
  "status": "대기중",
  "subject": "우리 강아지 발에 염증이 있어요",
  "content": "갑자기 발을 계속 핥고 아파하는데 병원 가야 할까요?",
  "ownerName": "김미라",
  "password": "1234",
  "email": "mira@example.com",
  "agreeEmail": "Y",
  "phoneNumber": "010-1234-5678",
  "agreeSms": "N",
  "agreePrivacy": "Y"
}
